### ISSUE TITLE
Book demo page

### ISSUE THREAD

**Issue by PiyuCoder** [PiyuCoder/beyondriffs#9]

**Comment by harshrajput177** [comment]
BOOK-DEMO PAGE

**Comment by Rohitaur** [comment]
[https://github.com/PiyuCoder/beyondriffs/issues/9#issue-2380301254](url)

**Comment by Rohitaur** [comment]
https://github.com/Rohitaur/Book_demo_pages

**Comment by Rohitaur** [comment]
/
